name: Build
on:
  push:
    tags:
      - 'v*'

jobs:
  build_on_win:
    runs-on: windows-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions@checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22
      - name: Check lint
        run: npm run lint
  publish_on_win:
    runs-on: windows-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22
      - name: install dependencies
        run: npm install
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
